version: "3.9"
services:
  db_apiusuarios:
    image: postgres:15-alpine
    container_name: postgres_apiusuarios_container
    ports:
      - "5440:5432"
    environment:
      POSTGRES_USER: pereiraapi
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: apiusuarios
    volumes:
      - ./data-apiusuarios:/var/lib/postgresql/data
