version: '3.8'

services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: userflashcards 
      POSTGRES_PASSWORD: passwordflashcards
      POSTGRES_DB: flashcards_db
    ports:
      # CRÍTICO: Mapea el puerto local 5433 al puerto interno 5432
      - '5433:5432' 
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: